import type { ImageLoaderProps } from "next/image"

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? ""

/**
 * next/image loader for the static export. Maps `/images/<name>.<ext>` at a requested width to
 * the WebP variant pre-generated by scripts/optimize-images.mjs, and prefixes the GitHub Pages
 * base path (next/image doesn't add basePath to `src` itself).
 */
export default function imageLoader({ src, width }: ImageLoaderProps) {
  const match = /^\/images\/([^/]+)\.(?:png|jpe?g|webp|avif)$/i.exec(src)
  if (!match) return `${basePath}${src}`
  return `${basePath}/images/optimized/${match[1]}-${width}.webp`
}
