import { clinic } from "@/lib/clinic"

/** Social share card, generated by src/app/og.png/route.tsx and referenced from layout metadata. */
export const ogImage = {
  url: "/og.png",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: `${clinic.name} — ${clinic.trustLine}, Bengaluru. Rated ${clinic.rating.value} on Google.`,
}
