import type { NextConfig } from "next";

import imageSizes from "./image-sizes.json";

// GitHub Pages serves this repo from /City-Poly-Clinic. The deploy workflow sets this from
// actions/configure-pages; leave it unset for local dev or a custom domain.
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const nextConfig: NextConfig = {
  // Static HTML export in `out/`, so the site can be hosted on GitHub Pages.
  // Cache Components / Partial Prefetching need a server, so they stay off for the static export.
  output: "export",
  basePath,
  images: {
    // No image server on a static host: serve WebP variants pre-generated by
    // scripts/optimize-images.mjs (widths must match image-sizes.json).
    loader: "custom",
    loaderFile: "./src/lib/image-loader.ts",
    deviceSizes: imageSizes.deviceSizes,
    imageSizes: imageSizes.imageSizes,
  },
  turbopack: {
    rules: {
      "*.css": {
        loaders: ["@tailwindcss/turbopack"],
        as: "*.css",
      },
    },
  },
};

export default nextConfig;
